### ISSUE TITLE
Browser type should be set.

### ISSUE THREAD

**Issue by precz** [precz/wpaana#2]
https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XUL/browser

**Comment by michaldybczak** [comment]
Yeap. Without it my app doesn't recognize the browser and all I can see is that it doesn't support this browser.

**Comment by timretout** [comment]
@precz I don't understand this bug - in app.xul I see <xul:browser type="content-primary"> - what am I missing?

@michaldybczak I believe your issue might be caused by User-Agent sniffing, which I have filed as issue #3 and patched in pull request #4 .

**Comment by timretout** [comment]
I'm guessing that this issue is referring to the github anti-framing code triggering, which suggests that window != window.top.

When I change "content-primary" to "content" in app.xul, that message goes away.  I'm not sure why this should be different.
